version: 2

models:
  - name: ods_syn_l1_v_beverage_sales_data_limpio
    description: "Vista limpia de ventas de bebidas sintéticas desde la capa Landing"
    columns:
      - name: order_id
        description: "Identificador único del pedido"
        tests:
          - not_null

      - name: customer_id
        description: "Identificador del cliente"
        tests:
          - not_null

      - name: product
        description: "Nombre del producto vendido"
        tests:
          - not_null

      - name: category
        description: "Categoría del producto"

      - name: customer_type
        description: "Tipo de cliente (nuevo, recurrente, etc.)"

      - name: unit_price
        description: "Precio unitario del producto"

      - name: quantity
        description: "Cantidad de productos comprados"

      - name: discount
        description: "Descuento aplicado"

      - name: total_price
        description: "Precio total con descuento"

      - name: region
        description: "Región geográfica de la compra"

      - name: order_date
        description: "Fecha del pedido"
  
  - name: ods_cli_l2_v_beverage_sales_data_categorizados
    description: "Vista con métricas para analizar"
    columns:
      - name: order_id
      - name: customer_id
        description: "Identificador del cliente"
      - name: order_date
        description: "Fecha del pedido"
      - name: num_products
      - name: total_quantity
        description: "Cantidad total de productos comprados"
      - name: total_spent
        description: "Monto total gastado en el pedido"
      - name: avg_price_per_product
      - name: previous_order_date
      - name: days_since_last_order

  - name: ods_cli_l3_v_beverage_sales_data_categorizados
    description: "Métricas para estudio"
    columns:
      - name: customer_id
      - name: num_orders
      - name: customer_value
      - name: avg_units_per_order
      - name: avg_spent_per_order
      - name: avg_days_between_orders
  
  - name: ods_cli_l4_v_beverage_sales_data_categorizados
    description: "Vista con métricas para analizar"
    columns:
      - name: order_id
      - name: customer_id
      - name: order_date
      - name: region
      - name: product
      - name: category
      - name: customer_type
      - name: num_products
      - name: total_quantity
      - name: total_spent
      - name: avg_price_per_product
      - name: previous_order_date
      - name: days_since_last_order
  
  - name: ods_cli_l5_v_beverage_sales_data_categorizados
    columns:
      - name: customer_id
      - name: avg_spent_per_order
      - name: avg_products_per_order
      - name: avg_days_between_orders
      - name: top_region
      - name: top_category
      - name: top_product
      - name: dominant_customer_type
  
  - name: ods_cli_l6_v_beverage_sales_data_categorizados
    columns:
      - name: customer_id
      - name: product
      - name: category
      - name: region
      - name: num_orders
      - name: total_quantity
      - name: total_spent
      - name: avg_unit_price
      - name: avg_discount
      - name: firs_order_date
      - name: last_order_date
      - name: num_lines
  
  - name: ods_cli_l7_v_beverage_sales_data_categorizados
    columns:
      - name: product_a
      - name: product_b
      - name: cooccurrence_count

tests:
      - unique:
          combination_of_columns:
            - order_id
            - product

sources:
  - name: lnd
    database: practicas_nubita
    schema: LND
    tables:
      - name: lnd_syn_t_beverage_sales_data